### ISSUE TITLE
Crashing on 'TerminationCondition' object has no attribute 'key'

### ISSUE THREAD

**Issue by sthallor** [snl-quest/snl-quest#27]
Using GLPK solver, BTM and Valuation with different inputs (ERCOT, CAISO)
[INFO   ] [Logger      ] Record log in C:\Users\sean\.kivy\logs\kivy_21-03-11_9.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\sean\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\sean\anaconda3\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.7639'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.7639'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [DMS         ] Successfully loaded valuation_dms.p.
[INFO   ] [DMS         ] Successfully loaded btm_dms.p.
[INFO   ] [Base        ] Start application main loop
[INFO   ] [DataManager ] Data bank scan complete.
[INFO   ] [ValuationBatch] ISO changed to CAISO.
[INFO   ] [ValuationBatch] Pricing node changed to EMBRCDR_2_N104.
[INFO   ] [ValuationBatch] Pricing node changed to DGAP_TEPC-APND.
[INFO   ] [ValuationBatch] ISO changed to ERCOT.
[INFO   ] [ValuationBatch] Pricing node selection reset.
[INFO   ] [ValuationBatch] Pricing node changed to HB_HOUSTON.
[INFO   ] [ValuationBatch] Revenue streams changed to ercot_arbreg.
[INFO   ] [DMS         ] Loading ERCOT DA-SPP
[INFO   ] [DMS         ] Data not yet in DMS, loading...
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Loading ERCOT DA-CCP
[INFO   ] [DMS         ] Data not yet in DMS, loading...
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [Optimizer   ] Setting fraction_reg_down to 0.25
[INFO   ] [Optimizer   ] Setting fraction_reg_up to 0.25
[INFO   ] [Optimizer   ] Setting Reserve_reg_max to 10.0
[INFO   ] [Optimizer   ] Setting Reserve_reg_min to 25.0
[INFO   ] [Optimizer   ] Setting State_of_charge_max to 90.0
[INFO   ] [Optimizer   ] Setting State_of_charge_min to 10.0
[INFO   ] [Optimizer   ] Setting State_of_charge_init to 65.0
[INFO   ] [Optimizer   ] Setting Power_rating to 10.0
[INFO   ] [Optimizer   ] Setting Energy_capacity to 5.5
[INFO   ] [Optimizer   ] Setting Round_trip_efficiency to 87.0
[INFO   ] [Optimizer   ] Setting Self_discharge_efficiency to 95.0
[WARNING] [ValuationOptimizer] Self_discharge_efficiency provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] Round_trip_efficiency provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] Reserve_reg_min provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] Reserve_reg_max provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] State_of_charge_min provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] State_of_charge_max provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] State_of_charge_init provided is greater than 1.0, interpreting as percentage...
GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --write C:\Users\sean\AppData\Local\Temp\tmpxfjvgwry.glpk.raw --wglp C:\Users\sean\AppData\Local\Temp\tmp5_9wd9ty.glpk.glp
 --cpxlp C:\Users\sean\AppData\Local\Temp\tmphcq53hg1.pyomo.lp
Reading problem data from 'C:\Users\sean\AppData\Local\Temp\tmphcq53hg1.pyomo.lp'...
2979 rows, 3722 columns, 10419 non-zeros
26061 lines were read
Writing problem data to 'C:\Users\sean\AppData\Local\Temp\tmp5_9wd9ty.glpk.glp'...
22334 lines were written
GLPK Simplex Optimizer, v4.65
2979 rows, 3722 columns, 10419 non-zeros
Preprocessing...
2974 rows, 3719 columns, 10410 non-zeros
Scaling...
 A: min|aij| =  8.700e-02  max|aij| =  1.000e+00  ratio =  1.149e+01
GM: min|aij| =  6.516e-01  max|aij| =  1.535e+00  ratio =  2.355e+00
EQ: min|aij| =  4.304e-01  max|aij| =  1.000e+00  ratio =  2.323e+00
Constructing initial basis...
Size of triangular part is 2974
      0: obj =   2.186338506e+02 inf =   1.083e+03 (746)
Perturbing LP to avoid stalling [201]...
   1492: obj =  -4.383968150e+02 inf =   0.000e+00 (0) 13
Removing LP perturbation [3505]...
*  3505: obj =   7.210148155e+04 inf =   0.000e+00 (0) 18
OPTIMAL LP SOLUTION FOUND
Time used:   0.5 secs
Memory used: 5.0 Mb (5247889 bytes)
Writing basic solution to 'C:\Users\sean\AppData\Local\Temp\tmpxfjvgwry.glpk.raw'...
6710 lines were written
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 503, in <module>
     QuEStApp().run()
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\Users\sean\anaconda3\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\sean\Desktop\NexESS\QuEST\snl-quest\es_gui\apps\valuation\batchrunscreen.kv", line 38, in <module>
     on_release: root.run_batch()
   File "C:\Users\sean\Desktop\NexESS\QuEST\snl-quest\es_gui\apps\valuation\batchrunscreen.py", line 77, in run_batch
     solved_ops, handler_status = handler.process_requests(requests)
   File "C:\Users\sean\Desktop\NexESS\QuEST\snl-quest\es_gui\apps\valuation\op_handler.py", line 121, in process_requests
     solved_op = self._solve_model(op)
   File "C:\Users\sean\Desktop\NexESS\QuEST\snl-quest\es_gui\apps\valuation\op_handler.py", line 148, in _solve_model
     op.run()
   File "C:\Users\sean\Desktop\NexESS\QuEST\snl-quest\es_gui\tools\optimizer.py", line 97, in run
     assert (results.solver.termination_condition.key == 'optimal')
 AttributeError: 'TerminationCondition' object has no attribute 'key'

**Comment by shanknatesh** [comment]
I am having the exact same issue but with the `ipopt` solver. Any luck?

**Comment by shanknatesh** [comment]
Downgrade `pyutilib` to `5.7.3` and `pyomo` to `5.6.8`.
