### ISSUE TITLE
Issue downloading rate structure

### ISSUE THREAD

**Issue by cancom84** [snl-quest/snl-quest#28]
Exception in thread Thread-2:
 Traceback (most recent call last):
   File "threading.py", line 917, in _bootstrap_inner
   File "threading.py", line 865, in run
   File "es_gui\apps\data_manager\rate_structure.py", line 296, in _execute_search
     self._download_utility_ref_table()
   File "es_gui\apps\data_manager\rate_structure.py", line 173, in _download_utility_ref_table
     data_iou = pd.read_csv(io.StringIO(data_down))
   File "site-packages\pandas\io\parsers.py", line 702, in parser_f
   File "site-packages\pandas\io\parsers.py", line 435, in _read
   File "site-packages\pandas\io\parsers.py", line 1139, in read
   File "site-packages\pandas\io\parsers.py", line 1995, in read
   File "pandas\_libs\parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
   File "pandas\_libs\parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
   File "pandas\_libs\parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
   File "pandas\_libs\parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
   File "pandas\_libs\parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
 pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 10

**Comment by tolutipmont** [comment]
Did you resolve this issue yet? I am experiencing the same error.

**Comment by cancom84** [comment]
The issue is due to the update of the utility list in OpenEI database. It has been resolved in patch 1.2.g. The code has been updated accordingly, the executable will be available soon.

**Comment by MoisheLefkowitz** [comment]
I'm experiencing the same error and have the 1.2.f executable version.  Does anyone know if there's a way to update the executable install with the posted 1.2.g files?  Or is there a way to download the rate structures seperately?
