### ISSUE TITLE
matplotlib import error

### ISSUE THREAD

**Issue by cancom84** [snl-quest/snl-quest#29]
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: DLL load failed while importing _window_sdl2: The specified module could not be found.
  File "C:\Users\tunguy\Anaconda3\lib\site-packages\kivy-2.0.0-py3.8-win-amd64.egg\kivy\core\__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "C:\Users\tunguy\Anaconda3\lib\site-packages\kivy-2.0.0-py3.8-win-amd64.egg\kivy\core\window\window_sdl2.py", line 27, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

 Traceback (most recent call last):
   File "main.py", line 55, in <module>
     from es_gui.apps.data_manager.data_manager import DataManager
   File "c:\work\quest\snl-quest\es_gui\apps\data_manager\data_manager.py", line 17, in <module>
     from es_gui.resources.widgets.common import LoadingModalView
   File "c:\work\quest\snl-quest\es_gui\resources\widgets\common.py", line 11, in <module>
     mpl.use('module://kivy.garden.matplotlib.backend_kivy')
   File "C:\Users\tunguy\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1171, in use
     plt.switch_backend(name)
   File "C:\Users\tunguy\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
     class backend_mod(matplotlib.backend_bases._Backend):
   File "C:\Users\tunguy\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
     locals().update(vars(importlib.import_module(backend_name)))
   File "C:\Users\tunguy\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "C:\Users\tunguy\Anaconda3\lib\site-packages\kivy-2.0.0-py3.8-win-amd64.egg\kivy\garden\__init__.py", line 180, in load_module
     return self._load_module(fullname, moddir)
   File "C:\Users\tunguy\Anaconda3\lib\site-packages\kivy-2.0.0-py3.8-win-amd64.egg\kivy\garden\__init__.py", line 183, in _load_module
     mod = imp.load_module(fullname, None, moddir,
   File "C:\Users\tunguy\Anaconda3\lib\imp.py", line 244, in load_module
     return load_package(name, filename)
   File "C:\Users\tunguy\Anaconda3\lib\imp.py", line 216, in load_package
     return _load(spec)
   File "C:\work\quest\snl-quest\libs\garden\garden.matplotlib\__init__.py", line 1, in <module>
     from kivy.garden.matplotlib.backend_kivy import FigureCanvasKivy,\
   File "C:\work\quest\snl-quest\libs\garden\garden.matplotlib\backend_kivy.py", line 256, in <module>
     from matplotlib import _png
 ImportError: cannot import name '_png' from 'matplotlib' (C:\Users\tunguy\Anaconda3\lib\site-packages\matplotlib\__init__.py)

**Comment by cancom84** [comment]
For now, please downgrade matplotlib to 3.1.3: 
pip install matplotlib 3.1.3
