### ISSUE TITLE
Kivy type error when running Performance Simulation

### ISSUE THREAD

**Issue by wpo14** [snl-quest/snl-quest#38]
This error is triggered when pressing the 'Go' button in the performance tool. 
 
Exception in thread Thread-7:
 Traceback (most recent call last):
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\threading.py", line 917, in _bootstrap_inner
     self.run()
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\threading.py", line 865, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\wolis\Documents\snl-quest\es_gui\apps\performance\performance_sim.py", line 91, in run_batch
     run_popup = PerformanceRunPopup()
   File "C:\Users\wolis\Documents\snl-quest\es_gui\apps\performance\performance_sim.py", line 546, in __init__
     super(PerformanceRunPopup, self).__init__(**kwargs)
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\modalview.py", line 195, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\wolis\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
     self.canvas = Canvas(opacity=self.opacity)
   File "kivy\graphics\instructions.pyx", line 608, in kivy.graphics.instructions.Canvas.__init__
   File "kivy\graphics\instructions.pyx", line 154, in kivy.graphics.instructions.InstructionGroup.__init__
   File "kivy\graphics\instructions.pyx", line 60, in kivy.graphics.instructions.Instruction.__init__
 TypeError: Cannot create graphics instruction outside the main Kivy thread

**Comment by wpo14** [comment]
Kivy does not allow altering graphics from outside the main thread. Since the simulation is run on a different thread a callback is necessary using the Clock object to open and close popups.

Closing the issue as it has been fixed.
