### ISSUE TITLE
kivy.uix.screenmanager.ScreenManagerException: No Screen with name "iso_select".

### ISSUE THREAD

**Issue by hchoi0211** [snl-quest/snl-quest#44]
I see the following errors and the QuESt window is closed when I try to go back to the previous window by clicking the button on the top left corner after I run valuation wizard and generate report.

[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\hchoi\Downloads\snl-quest-1.6-beta\snl-quest-1.6-beta\main.py", line 560, in <module>
     QuEStApp().run()
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\animation.py", line 371, in _update
     self.stop(widget)
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\animation.py", line 236, in stop
     self.dispatch('on_complete', widget)
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 420, in _on_complete
     self.screen_out.dispatch('on_leave')
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\hchoi\Downloads\snl-quest-1.6-beta\snl-quest-1.6-beta\es_gui\apps\valuation\wizard.py", line 45, in on_leave
     self.sm.clear_widgets(screens=self.sm.screens[1:])
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 1034, in clear_widgets
     remove_widget(widget)
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 1017, in remove_widget
     self.current = other
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 1063, in on_current
     self.transition.start(self)
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 377, in start
     self.screen_in.dispatch('on_pre_enter')
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\hchoi\Downloads\snl-quest-1.6-beta\snl-quest-1.6-beta\es_gui\apps\valuation\wizard.py", line 298, in on_pre_enter
     self.iso = self.manager.get_screen('iso_select').iso
   File "C:\Users\hchoi\Anaconda3\envs\quest\lib\site-packages\kivy\uix\screenmanager.py", line 1078, in get_screen
     raise ScreenManagerException('No Screen with name "%s".' % name)
 kivy.uix.screenmanager.ScreenManagerException: No Screen with name "iso_select".

**Comment by AlvaroFurlani** [comment]
@hchoi0211 I've been trying to replicate this problem but it is working normally for me. The list below is the step-by-step actions that I took; could you confirm if that is the situation where you received the error message?

1. QuESt Valuation > Get started
2. Wizard
3. Get started
4. MISO > Next
5. Node AECI.ALTW > Next
6. Arbitrage > Next
7. 2021 > Next
8. Li-ion Battery > Next
9. Next
10. Generate report > Start > Let's do it! > Return
11. Click arrow on top left corner and go back to first screen of QuESt Valuation
